FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish ChurchAttendanceApp.csproj -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/out .
EXPOSE 8080
ENTRYPOINT ["dotnet", "ChurchAttendanceApp.dll"]