
GET http://localhost:5090/Member/
###
GET http://localhost:5090/Member/4
###
POST http://localhost:5090/Member/
Content-Type: application/json

{
    "memberId": "SDA-IzenTorres",
    "name": "Izen Torres",
    "gender": "Male",
    "birthday": "2004-07-02",
    "address": "Sta. Quiteria",
    "email": "izen@gmail.com",
    "membershipStatus": "Visitor",
    "attendanceDate": "2026-03-21",
    "dateRegistered": "2026-03-16"
}
###
PUT http://localhost:5090/Member/4
Content-Type: application/json

{
    "id": 4,
    "memberId": "SDA-IzenTorres",
    "name": "Izen Torres",
    "gender": "Male",
    "birthday": "2004-07-02",
    "dateBaptized": "2013-12-01",
    "address": "Sta. Quiteria",
    "email": "izen@gmail.com",
    "phone": "09762812013",
    "membershipStatus": "Sabbath School Member",
    "attendanceDate": "2026-03-21",
    "dateRegistered": "2026-03-16"
}
###
DELETE http://localhost:5090/Member/3

###
POST http://localhost:5090/Member/
Content-Type: application/json

{
    "memberId": "SDA-RutuelRhoyMendoza",
    "name": "Rutuel Rhoy Mendoza",
    "gender": "Male",
    "birthday": "2002-10-26",
    "dateBaptized": "2016-12-02",
    "address": "new zealand",
    "email": "rhoy@gmail.com",
    "phone": "09722812011",
    "membershipStatus": "Sabbath School Member",
    "attendanceDate": "2026-03-21",
    "dateRegistered": "2026-03-16"
}
###
POST http://localhost:5090/Member/
Content-Type: application/json

{
    "memberId": "SDA-EvanAyalin",
    "name": "Evan Ayalin",
    "gender": "Male",
    "birthday": "2004-07-15",
    "dateBaptized": "2021-04-01",
    "address": "rubyville",
    "email": "evan@gmail.com",
    "phone": "09992812099",
    "membershipStatus": "Visitor",
    "attendanceDate": "2026-03-21",
    "dateRegistered": "2026-03-16"
}